### ISSUE TITLE
Unable to install using cocoapods 0.21.0.rc1

### ISSUE THREAD

**Issue by bananos** [mapbox/DEPRECATED-mapbox-ios-sdk#265]
While trying to run 

```
pod install
```

I'm getting the following errors:

```
[!] An error occurred while processing the post-install hook of MapBox (1.0.2).

undefined method `copy_resources_script_path' for <Pod::PodTarget name=Pods-MapBox platform=iOS 7.0>:Pod::PodTarget

/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/hooks/library_representation.rb:39:in `copy_resources_script_path'
/Users/bananos/.cocoapods/master/MapBox/1.0.2/MapBox.podspec:31:in `block (2 levels) in _eval_podspec'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-core-0.21.0.rc1/lib/cocoapods-core/specification.rb:419:in `call'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-core-0.21.0.rc1/lib/cocoapods-core/specification.rb:419:in `post_install!'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/installer.rb:502:in `run_spec_post_install_hook'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/installer.rb:477:in `block (3 levels) in run_post_install_hooks'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/installer.rb:475:in `each'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/installer.rb:475:in `block (2 levels) in run_post_install_hooks'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/installer.rb:473:in `each'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/installer.rb:473:in `block in run_post_install_hooks'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/user_interface.rb:113:in `message'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/installer.rb:472:in `run_post_install_hooks'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/installer.rb:115:in `block in generate_pods_project'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/user_interface.rb:52:in `section'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/installer.rb:110:in `generate_pods_project'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/installer.rb:88:in `install!'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/command/project.rb:38:in `run_install_with_update'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/command/project.rb:68:in `run'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/claide-0.3.2/lib/claide/command.rb:206:in `run'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/lib/cocoapods/command.rb:49:in `run'
/usr/local/Cellar/ruby/2.0.0-p195/lib/ruby/gems/2.0.0/gems/cocoapods-0.21.0.rc1/bin/pod:19:in `<top (required)>'
/usr/local/opt/ruby/bin/pod:23:in `load'
/usr/local/opt/ruby/bin/pod:23:in `<main>'

```

**Comment by incanus** [comment]
This should be fixed in the latest CocoaPods spec.
